### ISSUE TITLE
Site source down

### ISSUE THREAD

**Issue by Malaga82** [caiosweet/Home-Assistant-custom-components-DPC-Alert#11]
It seems the website source of component, http://www.protezionecivilepop.tk/ , is down.
Just to inform, if anyone can contact the site developer.
Thanks

**Comment by caiosweet** [comment]
Yes, there is also advertising.
If you want, you can contact the site [developer ](https://github.com/gpirrotta/protezionecivilepop/issues)

I think it is better to extract the data from the official source, but it is not simple. Web Scraping needed.

I was working on a new version also for the new nomenclature [Entity class names](https://developers.home-assistant.io/blog/2020/05/14/entity-class-names) for HomeAssistant v. 0.110.0

**Comment by caiosweet** [comment]
Giovanni perrotta's project is [here.](http://giovanni.pirrotta.it/blog/2018/05/17/protezione-civile-pop/)

I think it should be done:

1. [RSS feed](http://www.protezionecivile.gov.it/web/guest/dettaglio/-/journal/rss/351565?doAsGroupId=20182&refererPlid=42041&controlPanelCategory=current_site.content&_15_groupId=20182) to publish

2. link to download the file by date
`shp_file_day = "http://www.protezionecivile.gov.it/mapViewerPR/download.jsp?req=shp&day={}" # ex. 20200521`

or with Web Scraping, looking for the file link, with regex or BeautifulSoup
`http://www.protezionecivile.gov.it/geoserver/bcr/shp/20200520_1526_shp.zip`
If you look closely, there is the time of publication that always changes (1526)

3. process the data

4. output the json

I'll try! OK, any help most welcome! :0)

**Comment by caiosweet** [comment]
It's now up, thank you.

**Comment by Malaga82** [comment]
Thanks for the details.
