### ISSUE TITLE
BinarySensorDevice is deprecated, modify dpcSensor

### ISSUE THREAD

**Issue by scapman** [caiosweet/Home-Assistant-custom-components-DPC-Alert#12]
Hi.
I have just upgraded to 0.110.1.
I am running Home Assistant 0.110.1 on HassOS 3.13

I now get this warning:

Logger: homeassistant.components.binary_sensor
Source: components/binary_sensor/__init__.py:174
Integration: Binary Sensor (documentation, issues)
First occurred: 19:37:30 (5 occurrences)
Last logged: 19:37:30

BinarySensorDevice is deprecated, modify dpcSensor to extend BinarySensorEntity
BinarySensorDevice is deprecated, modify dpcWarningsSensor to extend BinarySensorEntity

Thanks,
Andrea

**Comment by caiosweet** [comment]
Hi, fixed in v.1.2.4

Thanks,
Claudio :0)
