### ISSUE TITLE
Error after last update

### ISSUE THREAD

**Issue by naked-head** [caiosweet/Home-Assistant-custom-components-DPC-Alert#14]
After last update no sensor is working, this is what I got in my log:
  File "/home/homeassistant/.homeassistant/custom_components/dpc/binary_sensor.py", line 8, in <module>
    import feedparser
ModuleNotFoundError: No module named 'feedparser'

Home assistant version 0.109.6 without Hass
DPC version 1.2.4

**Comment by caiosweet** [comment]
Hi what is your system?  
Try in the manifest.json 
"requirements": ["feedparser==5.2.1"]

will be installed on restart.
let me know if it works.

**Comment by naked-head** [comment]
That's work!!! tanks. 
My system is a Raspberry pi 3B+ with raspbian buster, home assistant is installed in python environment.
