### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Malaga82** [caiosweet/Home-Assistant-custom-components-DPC-Alert#22]
**Describe the bug**
It's several days since stopped working at all

**Screenshots**

 [homeassistant.components.binary_sensor] Error while setting up dpc platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/dpc/binary_sensor.py", line 70, in async_setup_platform
    await updater.async_update()
  File "/config/custom_components/dpc/binary_sensor.py", line 163, in async_update
    self.dpc_output = await self.fetch_all()
  File "/config/custom_components/dpc/binary_sensor.py", line 184, in fetch_all
    dataList = await asyncio.gather(*tasks)
  File "/config/custom_components/dpc/binary_sensor.py", line 214, in fetch
    prevision_date = parse(prevision["date"]).date()
KeyError: 'date'

**Additional context**
HA version 0.115.6

**Comment by fer4droid** [comment]
Same for me.

HA version 2021.1.0

**Comment by caiosweet** [comment]
It seems that the problem is some missing data in the parsing response, in particular the date.
How can I reply to your mistake? What istat number are you using?

**Comment by fer4droid** [comment]
I'm using 037006 Bologna (BO)

**Comment by caiosweet** [comment]
> I'm using 037006 Bologna (BO)

Checked the source and the data is missing for Bologna.
I opened an issue at website source.
Waiting for an answer, as soon as I can, I will insert an exception in the code that if data is missing, it will generate a warning with the data of the source to ask.

**Comment by Malaga82** [comment]
the istat i check is 038004

**Comment by caiosweet** [comment]
> the istat i check is 038004

Now I see that the data is there, it should work, maybe a reboot is needed. 
There is still a problem to be fixed, I try to correct it.

**Comment by fer4droid** [comment]
Yes, after a reboot now it's work.
Thank you and hope to be fixed soon.

**Comment by caiosweet** [comment]
The problem does not depend on the component, but on the lack of data from the resource. I added a warning message if there is no data.
In this way the entities are still created but not updated, until the resource site fixes the problem, by requesting corrections to be made to the link that will be displayed in the warning message.

Hope this solves if a similar problem occurs again.
