### ISSUE TITLE
Link non esistenti.

### ISSUE THREAD

**Issue by pex81** [caiosweet/Home-Assistant-custom-components-DPC-Alert#36]
**Describe the bug**
I link italiani descritti non funzionano, esce sempre "pagina non trovata"

**Comment by caiosweet** [comment]
Si, vedo che ora, finalmente, il sito è in https! Quindi devo solo aggiornare i link.

[mappe](https://mappe.protezionecivile.gov.it/it/mappe-rischi/bollettino-di-criticita)

Probabilmente, questo componente dovrà essere riscritto da zero... e passare direttamente dal sito ufficiale o dalle pubblicazioni su github. Non so se avrò modo di farlo... vediamo.

**Comment by caiosweet** [comment]
> **Describe the bug**
> I link italiani descritti non funzionano, esce sempre "pagina non trovata"

Sto facendo dei cambiamenti, per ora dovrebbe funzionare, è tutto qui, nella versione [beta](https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert/tree/beta).

Puoi provarla attivando da hacs le versioni beta del componente dpc.

**Comment by caiosweet** [comment]
Corretti e rilasciato una nuova versione.
