### ISSUE TITLE
Home Assistant 2021.6.2 error

### ISSUE THREAD

**Issue by pex81** [caiosweet/Home-Assistant-custom-components-DPC-Alert#37]
**Describe the bug**
Ho HA 2021..6.1 e volevo aggiornare a 2021.6.2.
Provando al configurazione con Check Home Assistant configuration esce il seguente errore.

Testing configuration at /tmp/config
Failed config
  General Errors: 
    - Platform error binary_sensor.dpc - No module named 'dateutil'

Successful config (partial)

**Comment by caiosweet** [comment]
> **Describe the bug**
> Ho HA 2021..6.1 e volevo aggiornare a 2021.6.2.
> Provando al configurazione con Check Home Assistant configuration esce il seguente errore.
> 
> Testing configuration at /tmp/config
> Failed config
> General Errors:
> - Platform error binary_sensor.dpc - No module named 'dateutil'
> 
> Successful config (partial)

Sto rifacendo tutto. Allo stato attuale, il componente della versione Main non funziona, prova la [beta](https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert/tree/beta).

Basta attivare le versioni beta da hacs.

**Comment by caiosweet** [comment]
Eliminato l'uso di dateutil. Nuova versione tutta da verificare :0)
Attualmente posso dire che funziona come prima, sia su Raspberry con HassOS, che con Nuc con Supervisor.
Anche in ambiente virtuale non ho problemi.
