### ISSUE TITLE
Type is missing

### ISSUE THREAD

**Issue by chrisdaloa** [caiosweet/Home-Assistant-custom-components-DPC-Alert#4]
Ciao, non permette di installare il repository tramite HACS

Type is missing for 'caiosweet/Home-Assistant-custom-components-DPC-Alert'.

**Comment by caiosweet** [comment]
Ciao. Hanno cambiato metodo per lo store. Per adesso prova ad installare manualmente. Intanto verifico gli update di HACS.

**Comment by caiosweet** [comment]
Ciao chrisdaloa. Allora ho verificato reinstallando da zero tutto, e funziona.
Bisogna installare la versione 16.2/16.3 di HACS (necessaria anche per poi passare alla 17)
Dopo aver installato HACS ed integrato con il menu integrazioni(IMPORTANTE), nello store cerchi DPC e lo installi.
Dopo aver riavviato, aggiungi la configirazione del binary sensor e riavvia.
Il codice ISTAT va inserito correttamente come da guida, per non sbagliare, mettilo tra apici!
Se ci sono ancora problemi, ti prego di inserire la tua configurazione e il log dell'errore. Grazie.
