### ISSUE TITLE
Addon don't active

### ISSUE THREAD

**Issue by maury77** [caiosweet/Home-Assistant-custom-components-DPC-Alert#40]
![image](https://user-images.githubusercontent.com/35746732/127858025-73952054-4b7a-4908-983e-40606f7c12b8.png)

HA version is 2021.7.4

**Comment by caiosweet** [comment]
Can you please post debug logs related to the problem?
Can you uninstall and reinstall  the component?
Thanks!

I’m currently working on new version...

**Comment by maury77** [comment]
ago 05 19:18:59 sdomotica homeassistant[20007]: 2021-08-05 19:18:59 ERROR (MainThread) [custom_components.dpc] Timeout error fetching information from https://mappe.protezionecivile.gov.it/it/mappe-rischi/bollettino-di-criticita -
ago 05 19:18:59 sdomotica homeassistant[20007]: 2021-08-05 19:18:59 ERROR (MainThread) [custom_components.dpc] Error fetching dpc data:
ago 05 19:18:59 sdomotica homeassistant[20007]: 2021-08-05 19:18:59 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Allerta_Meteo' for dpc integration not ready yet: None; Retrying in background

**Comment by caiosweet** [comment]
Uhm Is the hardware a raspberry PI? What model? Do you use a wifi or lan connection?

Soon, I will release a new version, I will increase the timeout.

**Comment by caiosweet** [comment]
FYI, timeout (30sec) has been added to version 2021.8.0 if you wish to give it a go!

**Comment by maury77** [comment]
I tryed the new version ma the problem is present .. boh...

2021-08-06 09:30:49 ERROR (MainThread) [custom_components.dpc] Timeout error fetching information from https://mappe.protezionecivile.gov.it/it/mappe-rischi/bollettino-di-criticita - 
2021-08-06 09:30:49 ERROR (MainThread) [custom_components.dpc] Timeout error fetching information from https://mappe.protezionecivile.it/it/mappe-rischi/bollettino-di-vigilanza - 


2021-08-06 09:30:56 ERROR (MainThread) [custom_components.dpc] Error fetching dpc data: 
2021-08-06 09:30:56 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Allerta_Meteo' for dpc integration not ready yet: None; Retrying in background


I have raspberry PI3B+ with cable connection

**Comment by caiosweet** [comment]
> Richiesta HTTP inviata, in attesa di risposta... 302 Moved Temporarily
> Posizione: /it/mappe-rischi/bollettino-di-criticita/ [segue]

Good news. I think I understand the problem.
If you look at response 302, it indicates a redirect ...

the problem is the incomplete url, a slash is missing at the end.

I make a new version with the fix.

**Comment by caiosweet** [comment]
If you want to try again ... version 2021.8.1 is out.

**Comment by maury77** [comment]
I try new version , the problem persist for me 

I would try to look better what happens on my rasp

**Comment by caiosweet** [comment]
Ok. 
Also check that the coordinates entered are decimal. (example Milan 45.4773 9.1815)
You could also turn on debug logging for the component.

In configuration.yaml
```
logger:
  default: warn
  logs:
    custom_components.dpc: debug
```

**Comment by caiosweet** [comment]
I have tried to replicate your error on a RPI3b+, and I have not encountered this problem ... 😖 
Anyway, I have made a new beta, where, as a first attempt, it tries to take bulletin ID directly from GitHub.

If you want to try it, turn on the beta switch in HACS, and install version 2021.8.1b.

**Comment by maury77** [comment]
NOW is working

**Comment by caiosweet** [comment]
Okay, glad it works for you now. I put the beta in master. Thanks for the test: 0)
