### ISSUE TITLE
Source: custom_components/dpc/api.py:315

### ISSUE THREAD

**Issue by micium** [caiosweet/Home-Assistant-custom-components-DPC-Alert#46]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.dpc
Source: custom_components/dpc/api.py:315
Integration: Dipartimento Protezione Civile (documentation, issues)
First occurred: 21:38:11 (2 occurrences)
Last logged: 21:38:11

Unexpected error exception occured for https://api.github.com/repos/pcm-dpc/DPC-Bollettini-Criticita-Idrogeologica-Idraulica/contents/files/all: {}
Traceback (most recent call last):
  File "/config/custom_components/dpc/api.py", line 281, in api_fetch
    fetched = {url: self.get_id_from_api(jdata, self._str_today)}
  File "/config/custom_components/dpc/api.py", line 319, in get_id_from_api
    return self.get_id_from_api(data, self._str_yesterday)
  File "/config/custom_components/dpc/api.py", line 319, in get_id_from_api
    return self.get_id_from_api(data, self._str_yesterday)
  File "/config/custom_components/dpc/api.py", line 319, in get_id_from_api
    return self.get_id_from_api(data, self._str_yesterday)
  [Previous line repeated 982 more times]
  File "/config/custom_components/dpc/api.py", line 315, in get_id_from_api
    for item in reversed(data):
RecursionError: maximum recursion depth exceeded while calling a Python object

 - OS: Home Assistant 2022.2.1

**Comment by caiosweet** [comment]
Please try the new version just released (2022.2.0 Fixed URL api)

**Comment by micium** [comment]
With the new version, the problem seems fixed.

Thanks

**Comment by micium** [comment]
Issue fixed
