### ISSUE TITLE
Error fetching dpc data:

### ISSUE THREAD

**Issue by azzis77** [caiosweet/Home-Assistant-custom-components-DPC-Alert#48]
Salve, 
Nel registro da qualche giorno ho questo errore:
(Home Assistant versione 2022.3.3) installata su PC.

Logger: custom_components.dpc
Source: helpers/update_coordinator.py:219
Integration: Dipartimento Protezione Civile (documentation, issues)
First occurred: 8 marzo 2022, 16:18:50 (961 occurrences)
Last logged: 13:34:49

Error fetching dpc data:

Logger: custom_components.dpc
Source: custom_components/dpc/api.py:189
Integration: Dipartimento Protezione Civile (documentation, issues)
First occurred: 8 marzo 2022, 16:18:50 (961 occurrences)
Last logged: 13:34:49

Error parsing information from https://mappe.protezionecivile.gov.it/it/mappe-rischi/bollettino-di-criticita - timeout() got an unexpected keyword argument 'loop'

**Comment by caiosweet** [comment]
Ciao, nei giorni scorsi stavo cercando di correggere alcuni errori, ho caricato ora, quello che sto utilizzando sul raspberry e nuc. Questa versione è scaricabile anche con hacs, attivando la casella "mostra versioni beta". è la [beta 2022.2.3 diagnostics](https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert/releases/tag/v2022.2.3). Potresti provarla, e vedere se funziona? Se è possibile, attiva anche il log per il componte.

In configuration.yaml

```
logger:
  default: warn
  logs:
    custom_components.dpc: debug
```

Ho anche aggiunto il diagnostics, ma ancora da completare :)

**Comment by azzis77** [comment]
Ottimo, fatto tutto e per ora funziona alla grande
Grazie boss!!

**Comment by azzis77** [comment]
Ottimo, fatto tutto e per ora funziona alla grande
Grazie boss!!
