### ISSUE TITLE
Nuovo tentativo di configurazione: None

### ISSUE THREAD

**Issue by auino** [caiosweet/Home-Assistant-custom-components-DPC-Alert#55]
Dopo aver configurato l'integrazione, compare il seguente messaggio:

`Nuovo tentativo di configurazione: None`

**Comment by caiosweet** [comment]
Ciao, mai visto prima :( faccio una prova su un raspberry 3 con tutto aggiornato.
Considera che è da un po' che non aggiorno, ma sul NUC con Proxmox con una VM di Home Assistant continua a funzionare :D 
Suppongo che hai seguito passo passo le istruzioni nel readme, provato un riavvio? 
Potresti dirmi su che sistema gira Home Assistant?

**Comment by caiosweet** [comment]
Eccomi qui, purtroppo sul raspberry non ho HACS, quindi ho eliminato la cartella dpc dai custom components, riavviato, scaricato da Github la versione Main, copiata la cartella dpc dal file zip e incollata nel percorso config/custom_components/
Riavviato, e installato da integrazioni.

Quello che posso immaginare, è il problema del timeout su connessioni lente o poco stabili, 10 secondi vedo che per molti non bastano. Forse i tentativi di configurazione, sono dovuti a questo [timeout](https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert/issues/54)

**Comment by auino** [comment]
Grazie @caiosweet. Dopo un po' di tempo, evidentemente dopo qualche tentativo, l'integrazione si è messa a funzionare correttamente. E' possibile che il problema sia dovuto ad un timeout: in caso si verificasse nuovamente, riapro la issue. Grazie ancora.

**Comment by caiosweet** [comment]
Okappa. Ma purtroppo ne sono certo :D è da tempo che vorrei salvare i dati su disco, per ovviare a questo problema e ottimizzare i tempi di riavvio. Comunque, se sei in grado, potresti modificare il timeout a 20 o più secondi, direttamente nel file api.py. Da notare che sono 8 file di origine, ed il timeout è per singolo file. La richiesta si ripete solo per quei file che non hanno ricevuto risposta dal server. 
In ogni caso, cercherò di ritornarci sul programma appena possibile e trovare delle soluzioni migliori :)

**Comment by auino** [comment]
Forse la cosa migliore sarebbe aggiungere un parametro di configurazione per il timeout, impostandolo di default a 20s (o 10s, come meglio ritieni).

**Comment by SiriosDev** [comment]
ad ogni update del core della "serie" 2022.9.X il problema si è ripresentata, ergo, credo che il problema sia l'update che rompe qualcosa nella configurazione.
