### ISSUE TITLE
Forecasts report unknown status

### ISSUE THREAD

**Issue by scantagithub** [caiosweet/Home-Assistant-custom-components-DPC-Alert#59]
After core update and integration update, the forecasts no longer work.
The sensors with today's alarms are functional while the sensors with tomorrow's forecasts report UNKNOWN status.
Also in the sensor.alert, among the list of attributes there are only today's values ​​and not tomorrow's

**Comment by caiosweet** [comment]
Yes, this is right. Tomorrow's sensor is populated only after the publication of the bulletin, usually around 4pm. Therefore tomorrow's value remains unknown until it is published by the DPC.
For more information on how data is published, you can read [here](https://github.com/pcm-dpc/DPC-Bollettini-Criticita-Idrogeologica-Idraulica#readme).
