### ISSUE TITLE
I/O in the event loop HA 0.109

### ISSUE THREAD

**Issue by Malaga82** [caiosweet/Home-Assistant-custom-components-DPC-Alert#6]
**Describe the bug**
as per HA 0.109 , there is a logic to detect possible blocking calls
**To Reproduce**
1. Go to 'dev tools'
2. Click on 'registry'
3. Scroll down to 'dpc values'

**Expected behavior**
no error logs

**Screenshots**
2020-04-29 18:34:39 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for dpc doing I/O at custom_components/dpc/binary_sensor.py, line 168: data = requests.get(url, timeout=10)

**Desktop (please complete the following information):**
 - OS: [win 10 ]
 - Browser [chrome]
 - Version [81.0.4044.129]

**Comment by caiosweet** [comment]
i think it needs asynchronous web requests i will try to fix

**Comment by Malaga82** [comment]
If you need any test I’m glad to help you.
Thanks

**Comment by caiosweet** [comment]
There are several ways to do it, I'll try this weekend, even if I'm not a developer.  Any help is welcome.

**Comment by Malaga82** [comment]
#7 
I'm testing this change, reading various PR for other official custom components, it should be enough.

**Comment by caiosweet** [comment]
Yes, for now the patch can be fine. it is OK. 
The code needs a revision, I hope as soon as possible. ;)

**Comment by Malaga82** [comment]
No problem :)
For now i didn't have any problem in my HA with that change and the log is completely gone.
When you'll release it i'll update to the official version.
Thanks

**Comment by caiosweet** [comment]
Yes the errors in the log are gone, but I get an error
Error setting up dpc - Check the istat number xxxxxx
I think I'll have to work on it... :0)

**Comment by Malaga82** [comment]
i don't have that error 😞

**Comment by Malaga82** [comment]
updated PR, i left some bracket in the function.
maybe that fix your error about istat.

**Comment by caiosweet** [comment]
Fixed in [v1.2.1](https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert/releases/tag/v1.2.1)
