### ISSUE TITLE
Detected that custom integration 'dpc' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4

### ISSUE THREAD

**Issue by micium** [caiosweet/Home-Assistant-custom-components-DPC-Alert#61]
Detected that custom integration 'dpc' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/dpc/__init__.py, line 73: hass.async_add_job(hass.config_entries.async_forward_entry_setup(entry, platform)), please create a bug report at https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert/issues

**Comment by micium** [comment]
any news ? is this a Pull request?

kind regards

**Comment by micium** [comment]
I resolved in replacing the string here below in the file init.py, line 73

old           hass.async_add_job(hass.config_entries.async_forward_entry_setup(entry, platform))
new         hass.async_create_task(hass.config_entries.async_forward_entry_setup(entry, platform))

**Comment by caiosweet** [comment]
Tanks @micium . Fixed in 2024.5.0
