### ISSUE TITLE
calls async_forward_entry_setup stop working in Home Assistant 2025.1.

### ISSUE THREAD

**Issue by micium** [caiosweet/Home-Assistant-custom-components-DPC-Alert#62]
Registratore: homeassistant.helpers.frame
Fonte: helpers/frame.py:151
Prima occorrenza: 10:13:11 (4 occorrenze)
Ultima registrazione: 10:13:11

Detected code that calls async_forward_entry_setup for integration dpc with title: Home and entry_id: 898c14588c83e4ee636685db4bad6bd6, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

after update HA to 2024.7.0

**Comment by micium** [comment]
The issue could be resolved in replacing the statement here below in the __init__.py line 73

old            hass.async_create_task(hass.config_entries.async_forward_entry_setup(entry, platform))
new           await hass.config_entries.async_forward_entry_setup(entry, platform)

**Comment by caiosweet** [comment]
Done!. Thank you so much @micium

**Comment by micium** [comment]
the correct statement is:

 await hass.config_entries.async_forward_entry_setups(entry, [platform])

"platform" in square brackets
